---
# tasks file for initialInstalls
- name: "update apt packages"
  apt:
    upgrade: yes
    update_cache: TRUE

- name: "install git and python3 and python pip"
  become: TRUE
  apt:
    name:
    - python3
    - python3-pip
    - git 
    state: latest
    update_cache: TRUE 

