---
# tasks file for initialInstalls
- name: "update apt packages"
  apt:
    upgrade: yes
    update_cache: true

- name: "install git and python3 and python pip"
  apt:
    name:
    - python3
    - python3-pip
    - pip
    - git
    state: latest
    update_cache: true

- name: Install pip
  apt:
    name: python-pip3
    update_cache: yes
    state: present