---
# tasks file for initialInstalls
- name: "update apt packages"
  apt:
    upgrade: "true"
    update_cache: "true"

- name: "install git and python3 and python pip"
  become: "true"
  apt:
    name:
    - python3
    - python3-pip
    - git 
    state: latest
    update_cache: "true"

