---
# tasks file for initialInstalls
- name: "update apt packages"
  apt:
    upgrade: yes
    update_cache: true

- name: "install git and python3 and python pip"
  apt:
    name:
    - python3
    - python3-pip
    - python 
    - git
    state: latest
    update_cache: true

