---
# tasks file for initialInstalls
- name: "update apt packages"
  apt:
    upgrade: full
    update_cache: "true"

- name: "install git and python3 and python pip"
  become: "true"
  apt:
    name:
    - python3
    - python3-pip
    - git 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-compose-plugin
    - python3-docker
    - python-is-python3
    - python
    - jsondiff
    state: latest
    update_cache: "true"
    force: yes

