---
# tasks file for initialInstalls
- name: "update apt packages"
  apt:
    upgrade: full
    update_cache: "true"

- name: "install git and python3 and python pip"
  become: "true"
  apt:
    name:
    - python3
    - python-pip
    - python3-pip
    - git
    - python3-docker
    - python-is-python3
    - python 
    state: latest
    update_cache: "true"
    force: yes

