---
# tasks file for swarminit
- name: "Init a new swarm with default parameters"
  docker_swarm:
    state: present
  register: swarm_info


- name: "Deploy app"
  docker_stack:
    state: present
    name: Book_generator
    compose:
      - /home/jenkins/docker-compose.yaml