- hosts: worker-group
  become: true
  roles:
  - initialinstalls
  - pipInstalls
  - dockerinstall


- hosts: manager-group
  connection: local
  become: true
  roles:
  - swarminit

- hosts: worker-group
  become: true
  roles:
  - swarmjoin